Curl
curl -X 'GET' \
  'http://localhost:5000/capital_gains?ticker=AAPL&api_token=t3stt%40ken' \
  -H 'accept: application/json'
 
 
<!doctype html>
<html lang=en>
  <head>
    <title>IndexError: index 0 is out of bounds for axis 0 with size 0
 // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script>
      var CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "xP69SY8x9ponrlxaYqbr";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>IndexError</h1>
<div class="detail">
  <p class="errormsg">IndexError: index 0 is out of bounds for axis 0 with size 0
</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul><li><div class="frame" id="frame-2338729287616">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\pandas\core\indexes\range.py"</cite>,
      line <em class="line">1018</em>,
      in <code class="function">__getitem__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>if isinstance(key, slice):</pre>
<pre class="line before"><span class="ws">            </span>return self._getitem_slice(key)</pre>
<pre class="line before"><span class="ws">        </span>elif is_integer(key):</pre>
<pre class="line before"><span class="ws">            </span>new_key = int(key)</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line current"><span class="ws">                </span>return self._range[new_key]
<span class="ws">                </span>       ^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except IndexError as err:</pre>
<pre class="line after"><span class="ws">                </span>raise IndexError(</pre>
<pre class="line after"><span class="ws">                    </span>f&#34;index {key} is out of bounds for axis 0 with size {len(self)}&#34;</pre>
<pre class="line after"><span class="ws">                </span>) from err</pre>
<pre class="line after"><span class="ws">        </span>elif is_scalar(key):</pre></div>
</div>

<li><div class="exc-divider">The above exception was the direct cause of the following exception:</div>
<li><div class="frame" id="frame-2338729318512">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1498</em>,
      in <code class="function">__call__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>) -&gt; cabc.Iterable[bytes]:</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>
<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>
<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)
<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre></div>
</div>

<li><div class="frame" id="frame-2338729326720">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1476</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.handle_exception(e)
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre>
<pre class="line after"><span class="ws">                </span>raise</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-2338729326864">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1473</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>error: BaseException | None = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre></div>
</div>

<li><div class="frame" id="frame-2338729327008">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">882</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>request_started.send(self, _async_wrapper=self.ensure_sync)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)
<span class="ws">            </span>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre>
<pre class="line after"><span class="ws">        </span>self,</pre>
<pre class="line after"><span class="ws">        </span>rv: ft.ResponseReturnValue | HTTPException,</pre></div>
</div>

<li><div class="frame" id="frame-2338729327152">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">880</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>request_started.send(self, _async_wrapper=self.ensure_sync)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()
<span class="ws">                </span>     ^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre></div>
</div>

<li><div class="frame" id="frame-2338729327296">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py"</cite>,
      line <em class="line">865</em>,
      in <code class="function">dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>and req.method == &#34;OPTIONS&#34;</pre>
<pre class="line before"><span class="ws">        </span>):</pre>
<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line before"><span class="ws">        </span>view_args: dict[str, t.Any] = req.view_args  # type: ignore[assignment]</pre>
<pre class="line current"><span class="ws">        </span>return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self) -&gt; Response:</pre>
<pre class="line after"><span class="ws">        </span>&#34;&#34;&#34;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws">        </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-2338729327440">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask_openapi3\scaffold.py"</cite>,
      line <em class="line">117</em>,
      in <code class="function">view_func</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">                        </span>view_object = view_class(view_kwargs=view_kwargs)</pre>
<pre class="line before"><span class="ws">                    </span>else:</pre>
<pre class="line before"><span class="ws">                        </span>view_object = view_class()</pre>
<pre class="line before"><span class="ws">                    </span>response = func(view_object, **func_kwargs)</pre>
<pre class="line before"><span class="ws">                </span>else:</pre>
<pre class="line current"><span class="ws">                    </span>response = func(**func_kwargs)
<span class="ws">                    </span>           ^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">                </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>if not hasattr(func, &#34;view&#34;):</pre>
<pre class="line after"><span class="ws">            </span>func.view = view_func</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-2338729280128">
  <h4>File <cite class="filename">"C:\Users\jfimb\Dropbox\AlphaGenFiles\pyedgarai\api.py"</cite>,
      line <em class="line">211</em>,
      in <code class="function">endpoint_func</code></h4>
  <div class="source "><pre class="line before"><span class="ws">    </span># Create the endpoint function with a unique name using a lambda</pre>
<pre class="line before"><span class="ws">    </span>def create_endpoint_func(request_model: Type[BaseRequestModel], element: str):</pre>
<pre class="line before"><span class="ws">        </span>def endpoint_func(query: request_model):</pre>
<pre class="line before"><span class="ws">            </span># Here you can perform authentication with query.api_token</pre>
<pre class="line before"><span class="ws">            </span># Call the get_stock_element function with appropriate parameters</pre>
<pre class="line current"><span class="ws">            </span>return get_stock_element(query.ticker, element)
<span class="ws">            </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>return endpoint_func</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span># Assign a unique name to the endpoint function</pre>
<pre class="line after"><span class="ws">    </span>endpoint_func = create_endpoint_func(request_model, element)</pre>
<pre class="line after"><span class="ws">    </span>endpoint_func.__name__ = f&#34;endpoint_func_{element}&#34;</pre></div>
</div>

<li><div class="frame" id="frame-2338729282720">
  <h4>File <cite class="filename">"C:\Users\jfimb\Dropbox\AlphaGenFiles\pyedgarai\src\pyedgarai\yfinance_endpoints.py"</cite>,
      line <em class="line">28</em>,
      in <code class="function">get_stock_element</code></h4>
  <div class="source "><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span># if its a dataframe convert to json</pre>
<pre class="line before"><span class="ws">    </span>if hasattr(response, &#39;to_dict&#39;):</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span># if index is 0, 1, ... do not transpose</pre>
<pre class="line current"><span class="ws">        </span>if not (response.index[0] in range(len(response.index))):
<span class="ws">        </span>        ^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>response = response.T</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">            </span># reset index</pre>
<pre class="line after"><span class="ws">            </span>response = response.reset_index()</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-2338729283152">
  <h4>File <cite class="filename">"C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\pandas\core\indexes\range.py"</cite>,
      line <em class="line">1020</em>,
      in <code class="function">__getitem__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>elif is_integer(key):</pre>
<pre class="line before"><span class="ws">            </span>new_key = int(key)</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>return self._range[new_key]</pre>
<pre class="line before"><span class="ws">            </span>except IndexError as err:</pre>
<pre class="line current"><span class="ws">                </span>raise IndexError(
<span class="ws">                </span>^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">                    </span>f&#34;index {key} is out of bounds for axis 0 with size {len(self)}&#34;</pre>
<pre class="line after"><span class="ws">                </span>) from err</pre>
<pre class="line after"><span class="ws">        </span>elif is_scalar(key):</pre>
<pre class="line after"><span class="ws">            </span>raise IndexError(</pre>
<pre class="line after"><span class="ws">                </span>&#34;only integers, slices (`:`), &#34;</pre></div>
</div>
</ul>
  <blockquote>IndexError: index 0 is out of bounds for axis 0 with size 0
</blockquote>
</div>

<div class="plain">
    <p>
      This is the Copy/Paste friendly version of the traceback.
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\pandas\core\indexes\range.py&#34;, line 1018, in __getitem__
    return self._range[new_key]
           ^^^^^^^^^^^^^^^^^^^^
IndexError: range object index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py&#34;, line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py&#34;, line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py&#34;, line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py&#34;, line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py&#34;, line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py&#34;, line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask_openapi3\scaffold.py&#34;, line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\Dropbox\AlphaGenFiles\pyedgarai\api.py&#34;, line 211, in endpoint_func
    return get_stock_element(query.ticker, element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\Dropbox\AlphaGenFiles\pyedgarai\src\pyedgarai\yfinance_endpoints.py&#34;, line 28, in get_stock_element
    if not (response.index[0] in range(len(response.index))):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &#34;C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\pandas\core\indexes\range.py&#34;, line 1020, in __getitem__
    raise IndexError(
IndexError: index 0 is out of bounds for axis 0 with size 0
</textarea>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\pandas\core\indexes\range.py", line 1018, in __getitem__
    return self._range[new_key]
           ^^^^^^^^^^^^^^^^^^^^
IndexError: range object index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\Dropbox\AlphaGenFiles\pyedgarai\api.py", line 211, in endpoint_func
    return get_stock_element(query.ticker, element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\Dropbox\AlphaGenFiles\pyedgarai\src\pyedgarai\yfinance_endpoints.py", line 28, in get_stock_element
    if not (response.index[0] in range(len(response.index))):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jfimb\anaconda3\envs\pyedgarai\Lib\site-packages\pandas\core\indexes\range.py", line 1020, in __getitem__
    raise IndexError(
IndexError: index 0 is out of bounds for axis 0 with size 0


-->